export const dialogTableMapping: {[key: string] : string } = {
    id: 'S. No',
    shop: 'Shop/Vendor',
    name: 'Medicine Name',
    phone: 'Contact',
    poc: 'Contact Person',
    location: 'Location',
    conditions: 'Conditions',
    preRequirement: 'Pre-Requirements',
    source: 'Source',
    verifiedAt: 'Verified At',
    verifiedBy: 'Verified By',
    oxygen: 'Oxygen',
    nonOxygen: 'Non Oxygen',
    icu: 'ICU',
    ventilators: 'Ventilator',
    availableQuanity: 'Quantity Available',
    cost: 'Cost',
    bloodGroup: 'Blood Group',
    covidNegativeOn: 'COVID -ve tested on',
    donorVolunteer: 'Donor/Volunteer',
    availableFacilities: 'Facilities available',
    description: 'Resource Description',
    direction: 'Direction'
}